### ISSUE TITLE
Nothing happens when using the script

### ISSUE THREAD

**Issue by ShiftyOG** [Mojito-Fivem/qb-insidetrack#2]
So I can go to the marker and press [E] but then nothing ever happens 
In the client/client.lua OpenInsideTrack function I added prints 
```
    Utils.Scaleform = RequestScaleformMovie('HORSE_RACING_CONSOLE')
    print('1')
    while not HasScaleformMovieLoaded(Utils.Scaleform) do
        Wait(0)
    end
    print('2')
```
Print 1 occurs but print 2 never appears. if I comment that loop out same thing happens at the next while loop for requesting audio for DLC_VINEWOOD/CASINO_GENERAL

**Comment by Mojito-Fivem** [comment]
Reger to prerequisites
