### ISSUE TITLE
Nothing on consoles

### ISSUE THREAD

**Issue by JoshuaTheBestGuy** [Mojito-Fivem/qb-insidetrack#4]
Hey, when the script is going I can't use the consoles![image](https://user-images.githubusercontent.com/47369562/132996050-9eda426c-0476-4774-939f-ed605678ec0c.jpeg)

**Comment by Mojito-Fivem** [comment]
No part of this script involves those.

**Comment by JoshuaTheBestGuy** [comment]
how do you use this script then, it's legit the inside track
