### ISSUE TITLE
No longer working after latest QB update

### ISSUE THREAD

**Issue by jawsoccer** [Mojito-Fivem/qb-insidetrack#5]
[38;5;161m[    c-scripting-core] Creating script environments for qb-insidetrack
[38;5;37m[script:qb-insidetrac] Error loading script server/server.lua in resource qb-insidetrack: @qb-insidetrack/server/server.lua:36: attempt to index a nil value (local 'QBCore')
[38;5;37m[script:qb-insidetrac] stack traceback:
[38;5;37m[script:qb-insidetrac] 	@qb-insidetrack/server/server.lua:36: in main chunk
[38;5;161m[    c-scripting-core] Failed to load script server/server.lua.

**Comment by Mojito-Fivem** [comment]
`after latest QB update` this. These new guys don't make their stuff backwards compatible so you can't expect it to work.
